# prooftrees-autochecks-dev.yml
# automatic testing for prooftrees dev

# https://github.com/latex3/hyperref/blob/adc36adbc3650db73329469b43afb0ee86e3c807/.github/workflows/main.yaml
# https://github.com/josephwright/siunitx/blob/main/.github/workflows/main.yaml

name: Automatic Checks for prooftrees dev

on:
  schedule:
    - cron: '18 3 * * *'
  push:
    branches: 
      - "*"
    paths:
      - '.github/workflows/prooftrees-autochecks-dev.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # addaswyd o https://github.com/latex3/latex2e/blob/develop/.github/workflows/main.yaml
  # update TL tree if needed
  texlive-cache-dev:
    runs-on: ubuntu-latest
    name: Update TeX Live cache
    outputs: 
      cache_key: ${{ steps.texlive.outputs.cache_key }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Install TeX Live
        id: texlive
        uses: zauguin/install-texlive@v4
        with:
          package_file: .github/tl_packages

  prooftrees-dev:
    # don't run if previous job failed (default)
    runs-on: ubuntu-latest
    name: "Test build: prooftrees dev"
    needs: texlive-cache-dev
    outputs:
      ctan_prooftrees_dev_output: ${{ steps.build-dev.outputs.ctan_ret }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Build ctan dev
        id: build-dev
        # uses: cfr42/nfssext/.github/actions/nfssext-autocheck-action@eeab7fc024553e35584805f40af881812b7e09a6
        uses: cfr42/nfssext/.github/actions/nfssext-autocheck-action@v0.2
        with:
          ctan: true
          # https://github.com/josephwright/siunitx/blob/549cad913591b92a3a199b7477a325866303bf29/.github/workflows/main.yaml
          # We need Ghostscript for XeTeX tests.
          # We need python3-pdfrw for memoize tests.
          extra_packages: ghostscript python3-pdfrw
          # cannot be built on github
          manifest: false
          module: prooftrees
          working_directory: prooftrees
          tds: false
          texlive_cache_key: ${{ needs.texlive-cache-dev.outputs.cache_key }}
          opts_ctan: "--dev"
      - name: Save ctan  dev build results
        if: ${{ !cancelled() }}
        id: save-outputs-dev
        shell: bash
        env: 
          checkret: ${{ steps.build-dev.outputs.check_ret }}
          ctanret: ${{ steps.build-dev.outputs.ctan_ret }}
          docret: ${{ steps.build-dev.outputs.doc_ret }}
        run: |
          allan=0
          [[ $checkret != 0 && $ctanret != 0 ]] && allan=1
          [[ $docret != 0 && $ctanret != 0 ]] && allan=1
          exit $allan

